fairseq-train \
    data-bin \
    --source-lang ice.g \
    --target-lang ice.p \
    --seed 42 \
    --arch transformer \
    --dropout .3 \
    --criterion label_smoothed_cross_entropy \
    --label-smoothing .1 \
    --optimizer adam \
    --lr .001 \
    --lr-scheduler inverse_sqrt \
    --batch-size 200 \
    --max-update 800 \
    --encoder-layers 4 \
    --encoder-embed-dim 256 \
    --encoder-ffn-embed-dim 1024 \
    --decoder-layers 4 \
    --decoder-embed-dim 256 \
    --decoder-ffn-embed-dim 1024 \
    --decoder-attention-heads 4 \
    --cross-self-attention \
    --layernorm-embedding \
    --no-epoch-checkpoints